### ISSUE TITLE
Architecture designed software

### ISSUE THREAD

**Issue by ajay-ca** [AnkitJodhani/3rdWeekofCloudOps#1]
Sorry for creating an issue for my query but I would really love to know the **software or website used for the architecture diagram**.
BTW I really love your content!!!
![architecture](https://github.com/AnkitJodhani/3rdWeekofCloudOps/assets/87013178/a3a62dfb-84bc-4477-a3b4-263fe0669105)

**Comment by ArtistYay** [comment]
+1 would love to know what you used to make the diagram 🙂 @AnkitJodhani

**Comment by AnkitJodhani** [comment]
I've used PowerPoint to create the above diagram. please check out my LinkedIn profile to get a frequent replies.
